<?php

namespace MauticPlugin\MauticShareBundle\Entity;

/**
 * ShareRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSharedCount($shareId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(s.id) FROM AppBundle:Share s WHERE s.parent=:shareId'
            )
            ->setParameters(['shareId' => $shareId])
            ->getSingleScalarResult();
    }
}
